### PR TITLE
Implement Token Authentication

### PR DESCRIPTION
**Pull request by wowi42**
Not working yet, I need some time to figure it out!

### CODE REVIEW

**Comment by tchiotludo** [comment]
strange! What is not working ?

**Comment by wowi42** [comment]
@tchiotludo authentication Token is always null...

**Comment by tchiotludo** [comment]
You are able to fill it on the flow, and it's null when you start an execution ?

**Comment by wowi42** [comment]
It has processed around 100,000 requests over the last week, so I think it's stable. @tchiotludo you can merge if it's ok for you

**Pull request merged**
